---
driver:
  name: vagrant
  require_chef_omnibus: false
  vm_hostname: 'alti-cookbook-test.kitchen.altiscale.com'
  network:
  - ['private_network', {ip: '10.10.10.99'}]
  customize:
    natdnsproxy1: 'off'
    natdnshostresolver1: 'off'

provisioner:
  name: chef_zero
  chef_client_path: '/usr/bin/chef-client'

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: prometheus-6.5.9
    driver_config:
      box: prometheus-6.5.9-201507302010
      box_url: https://s3-us-west-1.amazonaws.com/com.altiscale.vagrant/prometheus/boxes/prometheus-6.5.9-201507302010.box?AWSAccessKeyId=AKIAIA3IOFSJQ7L73JCQ&Expires=1755910245&Signature=W50E%2Ff4bLePJdzESjkf%2F401ybGc%3D

suites:
  - name: default
    run_list:
    - recipe[alti_pipeline_lib::default]
    - recipe[alti_skeleton::default]
