---
driver:
  name: vagrant
  require_chef_omnibus: false
  vm_hostname: 'alti-cobbler-test.kitchen.altiscale.com'
  network:
  - ['private_network', {ip: '10.10.10.99'}]
  customize:
    natdnsproxy1: 'off'
    natdnshostresolver1: 'off'
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  chef_client_path: '/usr/bin/chef-client'

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: prometheus-6.6.0
    driver_config:
      box: prometheus-6.6.0-201507161802
      box_url: https://s3-us-west-1.amazonaws.com/com.altiscale.vagrant/prometheus/boxes/prometheus-6.6.0-201507161802.box?AWSAccessKeyId=AKIAIKOVEEW6FVT5JBQA&Expires=1752649955&Signature=aGC2AvL9oAME0usGfwVgyTxKjec%3D

suites:
  - name: default
    run_list:
    - recipe[alti_pipeline_lib::default]      
    - recipe[cobbler-tester]
