source 'https://rubygems.org'

gem 'berkshelf', '~> 3.1.2'
gem 'berkshelf-api-client', '~> 1.2.1'
gem 'chef', '~> 11.12'
gem 'chefspec', '~> 4.2.0'
gem 'hashie', '~> 2.1.2'
gem 'kitchen-vagrant', '~> 0.15.0'
gem 'rubocop', '~> 0.28.0'
gem 'test-kitchen', '~> 1.3.1'
gem 'thor-foodcritic', '~> 1.1.0'
gem 'thor-scmversion', '~> 1.7.0'
gem 'yarjuf', '~> 2.0'
