# TODO: Add documentation

default[:cobbler][:settings][:allow_duplicate_hostnames] = 0
default[:cobbler][:settings][:allow_duplicate_ips] = 0
default[:cobbler][:settings][:allow_duplicate_macs] = 0
default[:cobbler][:settings][:allow_dynamic_settings] = 0
default[:cobbler][:settings][:anamon_enabled] = 0
default[:cobbler][:settings][:authn_pam_service] = 'login'
default[:cobbler][:settings][:auth_token_expiration] = 3600
default[:cobbler][:settings][:build_reporting_enabled] = 0
default[:cobbler][:settings][:build_reporting_sender] = ''
default[:cobbler][:settings][:build_reporting_email] = ['root@localhost']
default[:cobbler][:settings][:build_reporting_smtp_server] = 'localhost'
default[:cobbler][:settings][:build_reporting_subject] = ''
default[:cobbler][:settings][:build_reporting_ignorelist] = ['']
default[:cobbler][:settings][:cheetah_import_whitelist] = %w('random', 're', 'time')
default[:cobbler][:settings][:createrepo_flags] = '-c cache -s sha'
default[:cobbler][:settings][:default_kickstart] = '/var/lib/cobbler/kickstarts/default.ks'
default[:cobbler][:settings][:default_name_servers] = []
default[:cobbler][:settings][:default_ownership] = ['admin']
default[:cobbler][:settings][:default_password_crypted] = '$1$mF86/UHC$WvcIcX2t6crBz2onWxyac.'
default[:cobbler][:settings][:default_template_type] = 'cheetah'
default[:cobbler][:settings][:default_virt_bridge] = 'xenbr0'
default[:cobbler][:settings][:default_virt_file_size] = 5
default[:cobbler][:settings][:default_virt_ram] = 512
default[:cobbler][:settings][:default_virt_type] = 'xenpv'
default[:cobbler][:settings][:enable_gpxe] = 0
default[:cobbler][:settings][:enable_menu] = 1
default[:cobbler][:settings][:func_auto_setup] = 0
default[:cobbler][:settings][:func_master] = 'overlord.example.org'
default[:cobbler][:settings][:http_port] = 80
default[:cobbler][:settings][:kernel_options] =
  { 'ksdevice' => 'bootif', 'lang' => ' ', 'text' => nil }
default[:cobbler][:settings][:kernel_options_s390x] = {
  'RUNKS' => 1,
  'ramdisk_size' => 40000,
  'root' => '/dev/ram0',
  'ro' => nil,
  'ip' => 'off',
  'vnc' => nil
}
default[:cobbler][:settings][:ldap_server] = 'ldap.example.com'
default[:cobbler][:settings][:ldap_base_dn] = 'DC=example,DC=com'
default[:cobbler][:settings][:ldap_port] = 389
default[:cobbler][:settings][:ldap_tls] = 1
default[:cobbler][:settings][:ldap_anonymous_bind] = 1
default[:cobbler][:settings][:ldap_search_bind_dn] = ''
default[:cobbler][:settings][:ldap_search_passwd] = ''
default[:cobbler][:settings][:ldap_search_prefix] = 'uid='
default[:cobbler][:settings][:ldap_tls_cacertfile] = ''
default[:cobbler][:settings][:ldap_tls_keyfile] = ''
default[:cobbler][:settings][:ldap_tls_certfile] = ''
default[:cobbler][:settings][:mgmt_classes] = []
default[:cobbler][:settings][:mgmt_parameters] = { 'from_cobbler' => 1 }
default[:cobbler][:settings][:puppet_auto_setup] = 0
default[:cobbler][:settings][:sign_puppet_certs_automatically] = 0
default[:cobbler][:settings][:puppetca_path] = '/usr/bin/puppet'
default[:cobbler][:settings][:remove_old_puppet_certs_automatically] = 0
default[:cobbler][:settings][:manage_dhcp] = 0
default[:cobbler][:settings][:manage_dns] = 0
default[:cobbler][:settings][:bind_chroot_path] = ''
default[:cobbler][:settings][:bind_master] = '127.0.0.1'
default[:cobbler][:settings][:manage_tftpd] = 1
default[:cobbler][:settings][:manage_rsync] = 0
default[:cobbler][:settings][:manage_forward_zones] = []
default[:cobbler][:settings][:manage_reverse_zones] = []
default[:cobbler][:settings][:next_server] = '127.0.0.1'
default[:cobbler][:settings][:power_management_default_type] = 'ipmitool'
default[:cobbler][:settings][:power_template_dir] = '/etc/cobbler/power'
default[:cobbler][:settings][:pxe_just_once] = 0
default[:cobbler][:settings][:pxe_template_dir] = '/etc/cobbler/pxe'
default[:cobbler][:settings][:consoles] = '/var/consoles'
default[:cobbler][:settings][:redhat_management_type] = 'off'
default[:cobbler][:settings][:redhat_management_server] = 'xmlrpc.rhn.redhat.com'
default[:cobbler][:settings][:redhat_management_key] = ''
default[:cobbler][:settings][:redhat_management_permissive] = 0
default[:cobbler][:settings][:register_new_installs] = 0
default[:cobbler][:settings][:reposync_flags] = '-l -n -d'
default[:cobbler][:settings][:restart_dns] = 1
default[:cobbler][:settings][:restart_dhcp] = 1
default[:cobbler][:settings][:run_install_triggers] = 1
default[:cobbler][:settings][:scm_track_enabled] = 0
default[:cobbler][:settings][:scm_track_mode] = 'git'
default[:cobbler][:settings][:server] = '127.0.0.1'
default[:cobbler][:settings][:client_use_localhost] = 0
default[:cobbler][:settings][:client_use_https] = 0
default[:cobbler][:settings][:snippetsdir] = '/var/lib/cobbler/snippets'
default[:cobbler][:settings][:template_remote_kickstarts] = 0
default[:cobbler][:settings][:virt_auto_boot] = 1
default[:cobbler][:settings][:webdir] = '/var/www/cobbler'
default[:cobbler][:settings][:xmlrpc_port] = 25151
default[:cobbler][:settings][:yum_post_install_mirror] = 1
default[:cobbler][:settings][:yum_distro_priority] = 1
default[:cobbler][:settings][:yumdownloader_flags] = '--resolve'
default[:cobbler][:settings][:serializer_pretty_json] = 0
default[:cobbler][:settings][:replicate_rsync_options] = '-avzH'
default[:cobbler][:settings][:replicate_repo_rsync_options] = '-avzH'
default[:cobbler][:settings][:always_write_dhcp_entries] = 0
